package com.darkoverlordofdata.entitas.demo
/**
 * Entitas Generated Components for com.darkoverlordofdata.entitas.demo
 *
 * do not edit this file
 */

import com.darkoverlordofdata.entitas.IComponent


class BoundsComponent() : IComponent {
    var radius:Float = 0f
}

class BulletComponent() : IComponent {
    var false:undefined? = null
}

class DestroyComponent() : IComponent {
    var false:undefined? = null
}

class EnemyComponent() : IComponent {
    var false:undefined? = null
}

class ExpiresComponent() : IComponent {
    var delay:Float = 0f
}

class FiringComponent() : IComponent {
    var false:undefined? = null
}

class HealthComponent() : IComponent {
    var currentHealth:Float = 0f
    var maximumHealth:Float = 0f
}

class LayerComponent() : IComponent {
    var ordinal:com.darkoverlordofdata.entitas.demo.Layer? = null
}

class PlayerComponent() : IComponent {
    var false:undefined? = null
}

class PositionComponent() : IComponent {
    var x:Float = 0f
    var y:Float = 0f
}

class ResourceComponent() : IComponent {
    var name:String = ""
}

class ScaleComponent() : IComponent {
    var x:Float = 0f
    var y:Float = 0f
}

class ScoreComponent() : IComponent {
    var value:Int = 0
}

class SoundEffectComponent() : IComponent {
    var effect:com.darkoverlordofdata.entitas.demo.Effect? = null
}

class TintComponent() : IComponent {
    var r:Float = 0f
    var g:Float = 0f
    var b:Float = 0f
    var a:Float = 0f
}

class TweenComponent() : IComponent {
    var min:Float = 0f
    var max:Float = 0f
    var speed:Float = 0f
    var repeat:Boolean = false
    var active:Boolean = false
}

class VelocityComponent() : IComponent {
    var x:Float = 0f
    var y:Float = 0f
}

class ViewComponent() : IComponent {
    var sprite:com.badlogic.gdx.graphics.g2d.Sprite? = null
}

enum class Component {
    Bounds,
    Bullet,
    Destroy,
    Enemy,
    Expires,
    Firing,
    Health,
    Layer,
    Player,
    Position,
    Resource,
    Scale,
    Score,
    SoundEffect,
    Tint,
    Tween,
    Velocity,
    View,
    TotalComponents
}