package com.darkoverlordofdata.entitas.demo
/**
 * Entitas Generated Pool Extensions for com.darkoverlordofdata.entitas.demo
 *
 * do not edit this file
 */

import com.darkoverlordofdata.entitas.Pool
import com.darkoverlordofdata.entitas.Entity
import com.darkoverlordofdata.entitas.Matcher
