package com.darkoverlordofdata.entitas.demo
/**
 * Entitas Generated Components for com.darkoverlordofdata.entitas.demo
 *
 * do not edit this file
 */

import com.darkoverlordofdata.entitas.IComponent


data class BoundsComponent(var radius:Float=0f) : IComponent
data class BulletComponent(var active:Boolean=true) : IComponent
data class DestroyComponent(var active:Boolean=true) : IComponent
data class EnemyComponent(var active:Boolean=true) : IComponent
data class ExpiresComponent(var delay:Float = 0f) : IComponent
data class FiringComponent(var active:Boolean=true) : IComponent
data class HealthComponent(var currentHealth:Float = 0f, var maximumHealth:Float = 0f) : IComponent
data class LayerComponent(var ordinal:com.darkoverlordofdata.entitas.demo.Layer? = null) : IComponent
data class PlayerComponent(var active:Boolean=true) : IComponent
data class PositionComponent(var x:Float = 0f, var y:Float = 0f) : IComponent
data class ResourceComponent(var name:String = "") : IComponent
data class ScaleComponent(var x:Float = 0f, var y:Float = 0f) : IComponent
data class ScoreComponent(var value:Int = 0) : IComponent
data class SoundEffectComponent(var effect:com.darkoverlordofdata.entitas.demo.Effect? = null) : IComponent
data class TintComponent(var r:Float = 0f, var g:Float = 0f, var b:Float = 0f, var a:Float = 0f) : IComponent
data class TweenComponent(var min:Float = 0f, var max:Float = 0f, var speed:Float = 0f, var repeat:Boolean = false, var active:Boolean = false) : IComponent
data class VelocityComponent(var x:Float = 0f, var y:Float = 0f) : IComponent
data class ViewComponent(var sprite:com.badlogic.gdx.graphics.g2d.Sprite? = null) : IComponent

enum class Component {
    Bounds,
    Bullet,
    Destroy,
    Enemy,
    Expires,
    Firing,
    Health,
    Layer,
    Player,
    Position,
    Resource,
    Scale,
    Score,
    SoundEffect,
    Tint,
    Tween,
    Velocity,
    View,
    TotalComponents
}