package com.darkoverlordofdata.entitas.demo
/**
 * Entitas Generated Components for com.darkoverlordofdata.entitas.demo
 *
 * do not edit this file
 */

import com.darkoverlordofdata.entitas.IComponent


class BoundsComponent() : IComponent {
    var radius:Float = 0f
}

class BulletComponent() : IComponent {
    var active:Boolean = false
}

class ColorAnimationComponent() : IComponent {
    var redMin:Float = 0f
    var redMax:Float = 0f
    var redSpeed:Float = 0f
    var greenMin:Float = 0f
    var greenMax:Float = 0f
    var greenSpeed:Float = 0f
    var blueMin:Float = 0f
    var blueMax:Float = 0f
    var blueSpeed:Float = 0f
    var alphaMin:Float = 0f
    var alphaMax:Float = 0f
    var alphaSpeed:Float = 0f
    var redAnimate:Boolean = false
    var greenAnimate:Boolean = false
    var blueAnimate:Boolean = false
    var alphaAnimate:Boolean = false
    var repeat:Boolean = false
}

class EnemyComponent() : IComponent {
    var active:Boolean = false
}

class ExpiresComponent() : IComponent {
    var delay:Float = 0f
}

class FiringComponent() : IComponent {
    var active:Boolean = false
}

class HealthComponent() : IComponent {
    var currentHealth:Float = 0f
    var maximumHealth:Float = 0f
}

class ParallaxStarComponent() : IComponent {
    var active:Boolean = false
}

class PlayerComponent() : IComponent {
    var active:Boolean = false
}

class PositionComponent() : IComponent {
    var x:Float = 0f
    var y:Float = 0f
}

class ScaleAnimationComponent() : IComponent {
    var min:Float = 0f
    var max:Float = 0f
    var speed:Float = 0f
    var repeat:Boolean = false
    var active:Boolean = false
}

class SoundEffectComponent() : IComponent {
    var effect:com.darkoverlordofdata.entitas.demo.Effect? = null
}

class TintComponent() : IComponent {
    var r:Float = 0f
    var g:Float = 0f
    var b:Float = 0f
    var a:Float = 0f
}

class ViewComponent() : IComponent {
    var sprite:com.badlogic.gdx.graphics.g2d.Sprite? = null
}

class VelocityComponent() : IComponent {
    var x:Float = 0f
    var y:Float = 0f
}

class ScoreComponent() : IComponent {
    var value:Int = 0
}

class DestroyComponent() : IComponent {
    var active:Boolean = false
}

class MouseComponent() : IComponent {
    var x:Float = 0f
    var y:Float = 0f
}

class ScaleComponent() : IComponent {
    var x:Float = 0f
    var y:Float = 0f
}

class ResourceComponent() : IComponent {
    var name:String = ""
}

class LayerComponent() : IComponent {
    var ordinal:com.darkoverlordofdata.entitas.demo.Layer? = null
}

enum class Component {
    Bounds,
    Bullet,
    ColorAnimation,
    Enemy,
    Expires,
    Firing,
    Health,
    ParallaxStar,
    Player,
    Position,
    ScaleAnimation,
    SoundEffect,
    Tint,
    View,
    Velocity,
    Score,
    Destroy,
    Mouse,
    Scale,
    Resource,
    Layer,
    TotalComponents
}